version: "3.7"

# volumes:
#   ystore: {}
#   data: {
#     store: {}
#   }

services:
  ydaemon:
    build: .
    image: ydaemon
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ystore:/app/ystore
      - data/store:/app/store
    environment:
      - RPC_URI_FOR_1
      - RPC_URI_FOR_10
      - RPC_URI_FOR_250
      - RPC_URI_FOR_42161
      - WEBHOOK_SECRET
      - GRAPH_API_URI
      - SENTRY_DSN
      - SERVER_NAME
      - SENTRY_SAMPLE_RATE
      - LOG_LEVEL
    restart: always
