name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        working-directory: ./internal/...

    - name: Build
      run: go build -v cmd

    - name: Test
      run: go test -v ./...

    - name: Coverage
      uses: gwatts/go-coverage-action@v1.1.2
      with:
        working-directory: ./internal/...
        coverage-threshold: 90
